services:
    db:
        image: postgres:alpine
        restart: unless-stopped
        volumes:
            - ./data/db:/var/lib/postgresql/data
        ports:
            - 5432:5432
        
        environment:
            - POSTGRES_DB=clinic_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - clinic-network
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nest-backend
        ports:
            - '${PORT}:3000'
        volumes:
            - ./docker-data-backend-backups:/app/backups:rw
        environment:
            - DB_HOST=localhost
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_NAME=clinic_db
            - PORT=9921
            - COMPANY_NAME=SE
            - COMPANY_NUMBER=1111111111
            - COMPANY_ADDRESS=Address
        depends_on:
            - db
        networks:
            - clinic-network
networks:
    clinic-network:
        external: true
        